LOGSTASH_IP      = "192.168.50.101"
ELASTICSEARCH_IP = "192.168.50.102"
KIBANA_IP        = "192.168.50.103"

Vagrant.configure("2") do |config|
  config.vm.box = "centos7"

  config.vm.define "logstash" do |logstash|
    logstash.vm.hostname = "logstash"
    logstash.vm.network "private_network", ip: LOGSTASH_IP
    logstash.vm.provision "ansible" do |ansible|
      ansible.playbook = "logstash.yml"
    end
  end

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.hostname = "elasticsearch"
    elasticsearch.vm.network "private_network", ip: ELASTICSEARCH_IP
    elasticsearch.vm.provision "ansible" do |ansible|
      ansible.playbook = "elasticsearch.yml"
    end
  end

  config.vm.define "kibana" do |kibana|
    kibana.vm.hostname = "kibana"
    kibana.vm.network "private_network", ip: KIBANA_IP
    kibana.vm.network "forwarded_port", guest: 5601, host: 5601, guest_ip: "192.168.50.103"
    kibana.vm.provision "ansible" do |ansible|
      ansible.playbook = "kibana.yml"
    end
  end
end
