#!/bin/bash
set -e
# 用途:
# 用于启动一个容器,在容器内调试脚本
function main(){
  work_dir_basename=$(basename $PWD)
  container_id=$(docker run -d \
    --privileged=true --cap-add SYS_ADMIN --security-opt seccomp=unconfined \
    --cgroup-parent=docker.slice --cgroupns private \
    --tmpfs /tmp --tmpfs /run --tmpfs /run/lock\
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro\
    -v $PWD:/src/$work_dir_basename\
    -w /src/$work_dir_basename\
    -e LANG=en_US.utf8\
    -e container=docker\
    $default_image\
    /usr/sbin/init)
  cat <<EOF
输入以下命令进入容器
docker exec -it $(echo $container_id|cut -c -4) bash
EOF
}

default_image="centos:7"
main $@
