Vagrant.configure("2") do |config|
  config.vm.define "master01" do |master|
    master.vm.box = "centos7"
    master.vm.hostname = "master01"
    master.vm.network "private_network", ip: "192.168.50.11"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "master02" do |master|
    master.vm.box = "centos7"
    master.vm.hostname = "master02"
    master.vm.network "private_network", ip: "192.168.50.12"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "master03" do |master|
    master.vm.box = "centos7"
    master.vm.hostname = "master03"
    master.vm.network "private_network", ip: "192.168.50.13"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "node01" do |node|
    node.vm.box = "centos7"
    node.vm.hostname = "node01"
    node.vm.network "private_network", ip: "192.168.50.21"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "node02" do |node|
    node.vm.box = "centos7"
    node.vm.hostname = "node02"
    node.vm.network "private_network", ip: "192.168.50.22"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  ["docker-ce.yml", "kubernetes.yml"].each do |c|
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "#{c}"
    end
  end
end
