# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "redis.yml"
  end

  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network    "private_network", ip: "192.168.50.101"
  end

  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network    "private_network", ip: "192.168.50.102"
  end
  
  config.vm.define "node03" do |node03|
    node03.vm.hostname = "node03"
    node03.vm.network    "private_network", ip: "192.168.50.103"
  end
end
